services:
  goos-blog:
    image: docker.io/nginx:latest
    restart: always
    pull_policy: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wwwroot:/opt/wwwroot:ro
      - ./nginx/.empty:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy_backend

networks:
  proxy_backend:
    external: true
